<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE bookstore 
[
<!ELEMENT bookstore (genre+)>
<!ELEMENT genre (book+)>
<!ELEMENT book (title, author, description,price, image)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT author (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT price (#PCDATA)>
<!ELEMENT image (#PCDATA)>
<!ATTLIST genre category CDATA #REQUIRED>
<!ATTLIST title lang CDATA "en">
]>

<bookstore>
    <genre category="fiction">
        <book>
            <title lang="en">The Great Gatsby</title>
            <author>F. Scott Fitzgerald</author>
            <description>A tale of the American Dream in the roaring 1920s.</description>
            <price>10.99</price>
            <image>https://cdn.kobo.com/book-images/f37f5bc2-8171-475a-99fb-2f807813e085/1200/1200/False/the-great-gatsby-deluxe-hardbound-edition.jpg</image>
        </book>
        <book>
            <title lang="en">1984</title>
            <author>George Orwell</author>
            <description>A dystopian society ruled by Big Brother, where truth is manipulated.</description>
            <price>8.99</price>
            <image>https://m.media-amazon.com/images/I/715WdnBHqYL._UF1000,1000_QL80_.jpg</image>
        </book>
        <book>
            <title lang="en">Pride and Prejudice</title>
            <author>Jane Austen</author>
            <description>Elizabeth Bennet navigates love and societal expectations in Regency-era England.</description>
            <price>6.99</price>
            <image>https://rukminim2.flixcart.com/image/850/1000/kkec4280/book/d/h/d/pride-prejudice-original-imafzra6pfewjjwb.jpeg?q=20&amp;crop=false</image>
        </book>
    </genre>

    <genre category="fantasy">
        <book>
            <title lang="en">The Hobbit</title>
            <author>J.R.R. Tolkien</author>
            <description>Bilbo Baggins embarks on an adventure to reclaim treasure guarded by a dragon.</description>
            <price>13.49</price>
            <image>https://m.media-amazon.com/images/I/71V2v2GtAtL._AC_UF1000,1000_QL80_.jpg</image>
        </book>
        <book>
            <title lang="en">Harry Potter and the Sorcerer's Stone</title>
            <author>J.K. Rowling</author>
            <description>Harry Potter discovers he is a wizard and begins his adventure at Hogwarts.</description>
            <price>12.99</price>
            <image>https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1598823299i/42844155.jpg</image>
        </book>
        <book>
            <title lang="en">Eragon</title>
            <author>Christopher Paolini</author>
            <description>A young farm boy discovers a dragon egg and becomes a Dragon Rider.</description>
            <price>11.99</price>
            <image>https://m.media-amazon.com/images/I/91EJQU2B4cL.jpg</image>
        </book>
    </genre>

    <genre category="scifi">
        <book>
            <title lang="en">Dune</title>
            <author>Frank Herbert</author>
            <description>A young nobleman navigates politics and rebellion on the desert planet Arrakis.</description>
            <price>15.99</price>
            <image>https://images-cdn.ubuy.co.in/667a2941831b713f6862a35c-dune-the-graphic-novel-book-1-dune.jpg</image>
        </book>
        <book>
            <title lang="en">Ender's Game</title>
            <author>Orson Scott Card</author>
            <description>A young boy is trained to be humanity's savior against an alien threat.</description>
            <price>11.49</price>
            <image>https://m.media-amazon.com/images/I/91T-14y8aTL._AC_UF1000,1000_QL80_.jpg</image>
        </book>
        <book>
            <title lang="en">Neuromancer</title>
            <author>William Gibson</author>
            <description>A washed-up computer hacker is hired for one last job in a cyberpunk dystopia.</description>
            <price>13.99</price>
            <image>https://m.media-amazon.com/images/I/81m-rJnUdRL.jpg</image>
        </book>
    </genre>

    <genre category="mystery">
        <book>
            <title lang="en">The Girl with the Dragon Tattoo</title>
            <author>Stieg Larsson</author>
            <description>A journalist and a hacker investigate a 40-year-old missing persons case.</description>
            <price>14.99</price>
            <image>https://rukminim2.flixcart.com/image/850/1000/k8q8nm80/book/9/2/9/the-girl-with-the-dragon-tattoo-original-imafqzkpqcdz8ujc.jpeg?q=20&amp;crop=false</image>
        </book>
        <book>
            <title lang="en">Gone Girl</title>
            <author>Gillian Flynn</author>
            <description>A woman goes missing, and the mystery surrounding her disappearance unravels.</description>
            <price>12.49</price>
            <image>https://m.media-amazon.com/images/I/51yPqOEB0FL._AC_UF350,350_QL50_.jpg</image>
        </book>
        <book>
            <title lang="en">Big Little Lies</title>
            <author>Liane Moriarty</author>
            <description>A story of family secrets, lies, and murder at a school.</description>
            <price>13.99</price>
            <image>https://m.media-amazon.com/images/I/71l2dN4K4vL._AC_UF350,350_QL50_.jpg</image>
        </book>
    </genre>

    <genre category="nonfi">
        <book>
            <title lang="en">Educated</title>
            <author>Tara Westover</author>
            <description>A memoir about a woman who grows up in a strict family in rural Idaho and later escapes to learn about the world.</description>
            <price>14.99</price>
            <image>https://m.media-amazon.com/images/I/71N2HZwRo3L._UF350,350_QL50_.jpg</image>
        </book>
        <book>
            <title lang="en">Becoming</title>
            <author>Michelle Obama</author>
            <description>The memoir of former First Lady Michelle Obama, tracing her life from childhood to the White House.</description>
            <price>16.99</price>
            <image>https://rukminim2.flixcart.com/image/850/1000/kufuikw0/book/z/z/8/becoming-original-imag7jnzvj5yhfwy.jpeg?q=90&amp;crop=false</image>
        </book>
        <book>
            <title lang="en">Sapiens: A Brief History of Humankind</title>
            <author>Yuval Noah Harari</author>
            <description>A thought-provoking exploration of the history of human beings, from ancient history to modern times.</description>
            <price>18.49</price>
            <image>https://m.media-amazon.com/images/I/61i4k7DWNFL._AC_UF1000,1000_QL80_.jpg</image>
        </book>
    </genre>
</bookstore>
